trigger:
- main

variables:
  - name: templatesPath
    value: $(Pipeline.Workspace)/resources/template$(Pipeline.Workspace)/resources/templates
  - name: parametersPath
    value: $(Pipeline.Workspace)/resources/template$(Pipeline.Workspace)/resources/parameters

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DeployCosmosAccount
    jobs:
    - job:
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Development(108a3e7f-249e-4671-8922-9545709e0add)'
            subscriptionId: '108a3e7f-249e-4671-8922-9545709e0add'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'blog-api'
            location: 'East US'
            templateLocation: 'Linked artifact'
            csmFile: '$(templatesPath)/template.json'
            csmParametersFile: '$(parametersPath)/parameters.json'
            deploymentMode: 'Incremental'
            deploymentName: 'CosmosAccount'