name: DeployAzureResources

on:
  workflow_dispatch:
    inputs:
      resourceName:
        type: choice
        description: 'Resource Name'
        options:
        - CosmosDB
        - Container Registries
        - App Service

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: blog-api
        template: resources/${{ github.event.inputs.resourceName }}/template.json
        parameters: resources/${{ github.event.inputs.resourceName }}/parameters.json
